### ISSUE TITLE
Padding around the search box and rounded corners

### ISSUE THREAD

**Issue by takdw** [KELiON/cerebro#461]
- [ ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

I wanted to change the padding around the search box but I couldn't achieve it. I tried to look in the CSS file but not much info is there. And I can see that there are multiple static values of height set in the constants/ui.js file. What is the right way to increase padding around the search box? And also what about rounded corners?

**Comment by kevyworks** [comment]
I guess this is possible if the following can be achieved:

1) Disable Native Shadow
2) Transparent Window

Granting above is done; making the styling moved to #root:

```
__________________________________________
| NativeWindow                                      |
|      __________________________________________
|      |                                                              |
|      |  HTML>Document>Body>#root         |
|      |_________________________________________|
| ________________________________________|

```

```css

#root {
   border-radius: 22px;
   box-shadow: 0 1px 6px 0 rgba(32, 33, 36, .28);
   background: #FFFFFF;
   border-radius: 22px;
   cursor: text;
   font-size: 18px;
   height: 44px;
   line-height: 36px;
   margin: 0 auto;
   opacity: 1;
   position: relative;
   padding: 15px;
}

#root.with-result-lists {
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}

```
